blank_issues_enabled: false
contact_links:
  - name: Hazel Community Support (Discord)
    url: https://thecherno.com/discord
    about: Please ask Hazel related questions in the game-engine-series thread.
