#pragma once

enum class MouseButtonCode
{
	// From glfw3.h
	HZ_MOUSE_BUTTON_1      = 0,
	HZ_MOUSE_BUTTON_2      = 1,
	HZ_MOUSE_BUTTON_3      = 2,
	HZ_MOUSE_BUTTON_4      = 3,
	HZ_MOUSE_BUTTON_5      = 4,
	HZ_MOUSE_BUTTON_6      = 5,
	HZ_MOUSE_BUTTON_7      = 6,
	HZ_MOUSE_BUTTON_8      = 7,
	HZ_MOUSE_BUTTON_LAST   = HZ_MOUSE_BUTTON_8,
	HZ_MOUSE_BUTTON_LEFT   = HZ_MOUSE_BUTTON_1,
	HZ_MOUSE_BUTTON_RIGHT  = HZ_MOUSE_BUTTON_2,
	HZ_MOUSE_BUTTON_MIDDLE = HZ_MOUSE_BUTTON_3
};
